services:
  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: testpassword
    restart: unless-stopped

  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped